In [35]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

***Read in the car sales data from a CSV file***

In [36]:
df = pd.read_csv("carsels.csv" ,delimiter=';')

In [37]:
df.head()

Source.Name model    year    price transmission  mileage fuelType    tax  \
0    audi.csv    A1  2017.0  12500.0       Manual  15735.0   Petrol  150.0   
1    audi.csv    A6  2016.0  16500.0    Automatic  36203.0   Diesel   20.0   
2    audi.csv    A1  2016.0  11000.0       Manual  29946.0   Petrol   30.0   
3    audi.csv    A4  2017.0  16800.0    Automatic  25952.0   Diesel  145.0   
4    audi.csv    A3  2019.0  17300.0       Manual   1998.0   Petrol  145.0   

    mpg  engineSize  
0  55.4         1.4  
1  64.2         2.0  
2  55.4         1.4  
3  67.3         2.0  
4  49.6         1.0

Source.Name model    year    price transmission  mileage fuelType    tax  \
0    audi.csv    A1  2017.0  12500.0       Manual  15735.0   Petrol  150.0   
1    audi.csv    A6  2016.0  16500.0    Automatic  36203.0   Diesel   20.0   
2    audi.csv    A1  2016.0  11000.0       Manual  29946.0   Petrol   30.0   
3    audi.csv    A4  2017.0  16800.0    Automatic  25952.0   Diesel  145.0   
4    audi.csv    A3  2019.0  17300.0       Manual   1998.0   Petrol  145.0   

    mpg  engineSize  
0  55.4         1.4  
1  64.2         2.0  
2  55.4         1.4  
3  67.3         2.0  
4  49.6         1.0

***Select only the columns we want to use for modeling***

In [38]:
df = df[["Source.Name", "model", "year", "transmission", "mileage", "price"]]

In [39]:
df.head(5)

Source.Name model    year transmission  mileage    price
0    audi.csv    A1  2017.0       Manual  15735.0  12500.0
1    audi.csv    A6  2016.0    Automatic  36203.0  16500.0
2    audi.csv    A1  2016.0       Manual  29946.0  11000.0
3    audi.csv    A4  2017.0    Automatic  25952.0  16800.0
4    audi.csv    A3  2019.0       Manual   1998.0  17300.0

Source.Name model    year transmission  mileage    price
0    audi.csv    A1  2017.0       Manual  15735.0  12500.0
1    audi.csv    A6  2016.0    Automatic  36203.0  16500.0
2    audi.csv    A1  2016.0       Manual  29946.0  11000.0
3    audi.csv    A4  2017.0    Automatic  25952.0  16800.0
4    audi.csv    A3  2019.0       Manual   1998.0  17300.0

In [40]:
df.shape[0]

118150

118150

In [41]:
df.isnull().sum()

Source.Name        0
model            155
year             247
transmission     155
mileage         1077
price           9610
dtype: int64

Source.Name        0
model            155
year             247
transmission     155
mileage         1077
price           9610
dtype: int64

***Drop rows with missing values***

In [42]:
df=df.dropna()

In [43]:
df.isnull().sum()

Source.Name     0
model           0
year            0
transmission    0
mileage         0
price           0
dtype: int64

Source.Name     0
model           0
year            0
transmission    0
mileage         0
price           0
dtype: int64

In [44]:
df.head(5)

Source.Name model    year transmission  mileage    price
0    audi.csv    A1  2017.0       Manual  15735.0  12500.0
1    audi.csv    A6  2016.0    Automatic  36203.0  16500.0
2    audi.csv    A1  2016.0       Manual  29946.0  11000.0
3    audi.csv    A4  2017.0    Automatic  25952.0  16800.0
4    audi.csv    A3  2019.0       Manual   1998.0  17300.0

Source.Name model    year transmission  mileage    price
0    audi.csv    A1  2017.0       Manual  15735.0  12500.0
1    audi.csv    A6  2016.0    Automatic  36203.0  16500.0
2    audi.csv    A1  2016.0       Manual  29946.0  11000.0
3    audi.csv    A4  2017.0    Automatic  25952.0  16800.0
4    audi.csv    A3  2019.0       Manual   1998.0  17300.0

In [45]:
set(df['Source.Name'])

{'audi.csv',
 'bmw.csv',
 'cclass.csv',
 'focus.csv',
 'ford.csv',
 'hyundi.csv',
 'merc.csv',
 'skoda.csv',
 'toyota.csv',
 'vauxhall.csv',
 'vw.csv'}

{'audi.csv',
 'bmw.csv',
 'cclass.csv',
 'focus.csv',
 'ford.csv',
 'hyundi.csv',
 'merc.csv',
 'skoda.csv',
 'toyota.csv',
 'vauxhall.csv',
 'vw.csv'}

***Clean up the source names and rename it to car***

In [46]:
def source(ch):
    return ch[:-4] 

In [47]:
df['Source.Name']=df['Source.Name'].apply(lambda x : source(x))

In [48]:
df = df.rename({"Source.Name": "car"}, axis=1)

In [49]:
df.head(5)

car model    year transmission  mileage    price
0  audi    A1  2017.0       Manual  15735.0  12500.0
1  audi    A6  2016.0    Automatic  36203.0  16500.0
2  audi    A1  2016.0       Manual  29946.0  11000.0
3  audi    A4  2017.0    Automatic  25952.0  16800.0
4  audi    A3  2019.0       Manual   1998.0  17300.0

car model    year transmission  mileage    price
0  audi    A1  2017.0       Manual  15735.0  12500.0
1  audi    A6  2016.0    Automatic  36203.0  16500.0
2  audi    A1  2016.0       Manual  29946.0  11000.0
3  audi    A4  2017.0    Automatic  25952.0  16800.0
4  audi    A3  2019.0       Manual   1998.0  17300.0

In [50]:
df.model.value_counts()

 Focus      10042
 C Class     7646
 Fiesta      6557
 Golf        4863
 Corsa       3441
            ...  
180             1
230             1
220             1
200             1
 Accent         1
Name: model, Length: 195, dtype: int64

 Focus      10042
 C Class     7646
 Fiesta      6557
 Golf        4863
 Corsa       3441
            ...  
180             1
230             1
220             1
200             1
 Accent         1
Name: model, Length: 195, dtype: int64

In [51]:
df.car=df.car.apply(lambda x : "merc" if x=="cclass" else x)

***Drop rows with invalid years***

In [52]:
i=df[df.year<2005].index
df=df.drop(i)

In [53]:
i=df[df.year==2060].index
df=df.drop(i)

***Encode categorical variables using label encoding***

In [54]:
from sklearn.preprocessing import LabelEncoder
le_cars = LabelEncoder()
df['car_encoded'] = le_cars.fit_transform(df['car'])
label_map_cars = dict(zip(le_cars.classes_, le_cars.transform(le_cars.classes_)))
label_map_cars


{'audi': 0,
 'bmw': 1,
 'focus': 2,
 'ford': 3,
 'hyundi': 4,
 'merc': 5,
 'skoda': 6,
 'toyota': 7,
 'vauxhall': 8,
 'vw': 9}

{'audi': 0,
 'bmw': 1,
 'focus': 2,
 'ford': 3,
 'hyundi': 4,
 'merc': 5,
 'skoda': 6,
 'toyota': 7,
 'vauxhall': 8,
 'vw': 9}

In [55]:
df['model_encoded'] = le_cars.fit_transform(df['model'])
label_map_models = dict(zip(le_cars.classes_, le_cars.transform(le_cars.classes_)))
label_map_models

{' 1 Series': 0,
 ' 2 Series': 1,
 ' 3 Series': 2,
 ' 4 Series': 3,
 ' 5 Series': 4,
 ' 6 Series': 5,
 ' 7 Series': 6,
 ' 8 Series': 7,
 ' A Class': 8,
 ' A1': 9,
 ' A3': 10,
 ' A4': 11,
 ' A5': 12,
 ' A6': 13,
 ' A7': 14,
 ' A8': 15,
 ' Adam': 16,
 ' Agila': 17,
 ' Amarok': 18,
 ' Amica': 19,
 ' Ampera': 20,
 ' Antara': 21,
 ' Arteon': 22,
 ' Astra': 23,
 ' Auris': 24,
 ' Avensis': 25,
 ' Aygo': 26,
 ' B Class': 27,
 ' B-MAX': 28,
 ' Beetle': 29,
 ' C Class': 30,
 ' C-HR': 31,
 ' C-MAX': 32,
 ' CC': 33,
 ' CL Class': 34,
 ' CLA Class': 35,
 ' CLC Class': 36,
 ' CLK': 37,
 ' CLS Class': 38,
 ' Caddy': 39,
 ' Caddy Life': 40,
 ' Caddy Maxi': 41,
 ' Caddy Maxi Life': 42,
 ' California': 43,
 ' Camry': 44,
 ' Caravelle': 45,
 ' Cascada': 46,
 ' Citigo': 47,
 ' Combo Life': 48,
 ' Corolla': 49,
 ' Corsa': 50,
 ' Crossland X': 51,
 ' E Class': 52,
 ' EcoSport': 53,
 ' Edge': 54,
 ' Eos': 55,
 ' Fabia': 56,
 ' Fiesta': 57,
 ' Focus': 58,
 ' Fox': 59,
 ' Fusion': 60,
 ' G Class': 61,
 ' GL Cl

{' 1 Series': 0,
 ' 2 Series': 1,
 ' 3 Series': 2,
 ' 4 Series': 3,
 ' 5 Series': 4,
 ' 6 Series': 5,
 ' 7 Series': 6,
 ' 8 Series': 7,
 ' A Class': 8,
 ' A1': 9,
 ' A3': 10,
 ' A4': 11,
 ' A5': 12,
 ' A6': 13,
 ' A7': 14,
 ' A8': 15,
 ' Adam': 16,
 ' Agila': 17,
 ' Amarok': 18,
 ' Amica': 19,
 ' Ampera': 20,
 ' Antara': 21,
 ' Arteon': 22,
 ' Astra': 23,
 ' Auris': 24,
 ' Avensis': 25,
 ' Aygo': 26,
 ' B Class': 27,
 ' B-MAX': 28,
 ' Beetle': 29,
 ' C Class': 30,
 ' C-HR': 31,
 ' C-MAX': 32,
 ' CC': 33,
 ' CL Class': 34,
 ' CLA Class': 35,
 ' CLC Class': 36,
 ' CLK': 37,
 ' CLS Class': 38,
 ' Caddy': 39,
 ' Caddy Life': 40,
 ' Caddy Maxi': 41,
 ' Caddy Maxi Life': 42,
 ' California': 43,
 ' Camry': 44,
 ' Caravelle': 45,
 ' Cascada': 46,
 ' Citigo': 47,
 ' Combo Life': 48,
 ' Corolla': 49,
 ' Corsa': 50,
 ' Crossland X': 51,
 ' E Class': 52,
 ' EcoSport': 53,
 ' Edge': 54,
 ' Eos': 55,
 ' Fabia': 56,
 ' Fiesta': 57,
 ' Focus': 58,
 ' Fox': 59,
 ' Fusion': 60,
 ' G Class': 61,
 ' GL Cl

In [56]:
df['transmission_encoded'] = le_cars.fit_transform(df['transmission'])
label_map_trans = dict(zip(le_cars.classes_, le_cars.transform(le_cars.classes_)))
label_map_trans


{'Automatic': 0, 'Manual': 1, 'Other': 2, 'Semi-Auto': 3}

{'Automatic': 0, 'Manual': 1, 'Other': 2, 'Semi-Auto': 3}

***Define the feature matrix (X) and target vector (y)***

In [57]:
X=df[['year','mileage','car_encoded','model_encoded','transmission_encoded']]
y=df['price']

***Train a linear regression model on the data***


In [58]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

LinearRegression()

***Make predictions using the linear regression model***

In [59]:
y_pred=linear_reg.predict(X)

***Calculate the root mean squared error (RMSE) of the linear regression model***

In [60]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
error = np.sqrt(mean_squared_error(y, y_pred))
print("Linear Regression RMSE:", error)

Linear Regression RMSE: 7877.705139750936
Linear Regression RMSE: 7877.705139750936


In [61]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)
y_pred=random_forest_reg.predict(X)

In [62]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
error = np.sqrt(mean_squared_error(y, y_pred))
print("Error Reult", error)

Error Reult 1672.3651939030547
Error Reult 1672.3651939030547


In [63]:
df.head(5)

car model    year transmission  mileage    price  car_encoded  \
0  audi    A1  2017.0       Manual  15735.0  12500.0            0   
1  audi    A6  2016.0    Automatic  36203.0  16500.0            0   
2  audi    A1  2016.0       Manual  29946.0  11000.0            0   
3  audi    A4  2017.0    Automatic  25952.0  16800.0            0   
4  audi    A3  2019.0       Manual   1998.0  17300.0            0   

   model_encoded  transmission_encoded  
0              9                     1  
1             13                     0  
2              9                     1  
3             11                     0  
4             10                     1

car model    year transmission  mileage    price  car_encoded  \
0  audi    A1  2017.0       Manual  15735.0  12500.0            0   
1  audi    A6  2016.0    Automatic  36203.0  16500.0            0   
2  audi    A1  2016.0       Manual  29946.0  11000.0            0   
3  audi    A4  2017.0    Automatic  25952.0  16800.0            0   
4  audi    A3  2019.0       Manual   1998.0  17300.0            0   

   model_encoded  transmission_encoded  
0              9                     1  
1             13                     0  
2              9                     1  
3             11                     0  
4             10                     1

In [64]:
random_forest_reg.predict(np.array([2017,15735,0,9,1]).reshape(1, -1))

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([13213.05])

array([13213.05])

***Save & Load the trained model and label encoders to a file using pickle***

In [65]:
import pickle

In [66]:
data = {"model": random_forest_reg, "le_cars": le_cars}
with open('model.pkl', 'wb') as f:
    pickle.dump(random_forest_reg, f)

with open('model.pkl', 'rb') as f:
    model_loaded = pickle.load(f)

In [67]:
y_pred =  model_loaded.predict(X)
y_pred

array([13213.05      , 18029.48      , 11592.76066667, ...,
        2857.38      ,  1575.33      ,  2381.64      ])

array([13213.05      , 18029.48      , 11592.76066667, ...,
        2857.38      ,  1575.33      ,  2381.64      ])

**Gradio Interface**

In [73]:
import gradio as gr
def predict_price(year, mileage, car, model, transmission):
    car_encoded = car_encoder_loaded.transform([car])[0]
    model_encoded = le_cars.transform([model])[0]
    transmission_encoded = le_cars.transform([transmission])[0]
    features = np.array([year, mileage, car_encoded, model_encoded, transmission_encoded]).reshape(1, -1)
    prediction = model_loaded.predict(features)
    return prediction[0]


car_types = df['car'].unique().tolist()
model_names = df['model'].unique().tolist()
transmission_types = df['transmission'].unique().tolist()

iface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.inputs.Number(label="Year"),
        gr.inputs.Slider(minimum=0, maximum=200000, default=50000, label="Mileage"),
        gr.inputs.Dropdown(car_types, label="Car Type"),
        gr.inputs.Dropdown(model_names, label="Model"),
        gr.inputs.Dropdown(transmission_types, label="Transmission"),
    ],
    outputs="number",
    title="Car Price Predictor",
    description="Predict the price of a car based on its features.",
    examples=[
        [2017, 15735, car_types[0], model_names[0], transmission_types[0]],
        [2020, 50000, car_types[1], model_names[1], transmission_types[1]],
    ]
)

iface.launch()

C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\inputs.py:59: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\inputs.py:62: UserWarning: `optional` parameter is deprecated, and it has no effect
  super().__init__(value=default, label=label, optional=optional)
C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\inputs.py:89: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\inputs.py:93: UserWarning: `optional` parameter is deprecated, and it has no effect
  super().__init__(
C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\inputs.py:219: UserWarning: Usage of gradio.inputs 

Running on local URL:  http://127.0.0.1:7866

To create a public link, set `share=True` in `launch()`.
Running on local URL:  http://127.0.0.1:7866

To create a public link, set `share=True` in `launch()`.


Traceback (most recent call last):
  File "C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\skend\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\ProgramData\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "C:\Us